version: '3'

services:

  nginx:
    build:
      context: ./nginx
    volumes:
      - ../src:/var/www/mikisiki/public
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/default.conf:/etc/nginx/sites-available/default.conf

    ports:
      - "81:80"
      - "443:443"

  #php-fpm:
  #     build:
  #       context: ./php-fpm
  #     volumes:
  #       - ../src:/var/www