version: '3'

services:

  # ovde treba da dodam laravel, mariaDB, i php
  # link do laravela https://github.com/nemanjamil/examserver
  nginx:
    build:
      context: ./nginx
      args:
        - ARG_LATEST=latest
    image : nemanjamil/nginx
    volumes:
      - ./src:/var/www/mikisiki/public
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/default.conf:/etc/nginx/sites-available/default.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
          - php-fpm
    ports:
      - "81:80"
      - "443:443"

  # PHP
  php-fpm:
      build:
        context: ./php-fpm
      volumes:
        - ./src:/var/www/mikisiki/public

  # DATABASE
  database:
      build:
        context: ./database
      environment:
        - MYSQL_DATABASE=mydb
        - MYSQL_USER=myuser
        - MYSQL_PASSWORD=secret
        - MYSQL_ROOT_PASSWORD=docker
      volumes:
        - ./database/data.sql:/docker-entrypoint-initdb.d/data.sql

